services:
  postgres:
    image: postgres:alpine3.20
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - './config/postgres/_sql/:/docker-entrypoint-initdb.d/'

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
      MINIO_BROWSER_REDIRECT_URL: http://localhost/minio/ui
    volumes:
      - './attachments/minio-storage:/data'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  radiojournal-server:
    build: ./server
    environment:
      CONFIG_PATH: ${CONFIG_PATH}
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - minio

  radiojournal-client:
    build: ./client
    ports:
      - '5173:5173'

  radiojournal-admin-panel:
    build: ./admin-panel
    ports:
      - '5174:5174'

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - "./config/prometheus:/etc/prometheus"

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=http://nginx:80/grafana
    links:
      - prometheus:prometheus
    ports:
      - 3000:3000
    volumes:
      - "./config/grafana/dashboards:/etc/grafana/provisioning/dashboards"
      - "./config/grafana/datasources:/etc/grafana/provisioning/datasources"

  nginx:
    image: nginx:alpine3.19
    links:
      - prometheus:prometheus
      - radiojournal-admin-panel:radiojournal-admin-panel
      - radiojournal-client:radiojournal-client
      - radiojournal-server:radiojournal-server
      - minio:minio
      - grafana:grafana
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    ports:
      - 80:80
