env: dev
port: 8080
api_version: 1

minio:
  user: miniouser
  password: miniopass
  buckets:
    - name: videos
      content_types: video/mp4
    - name: documents
      content_types: application/pdf
    - name: images
      content_types: image/jpeg

postgres:
  password: testpass
  user: testuser
  name: radio-journal

auth:
  admin_password: admin
  admin_login: admin
  secret: secret
  token_lifetime: 24

monitoring:
  content_types: application/pdf
